version: '3'
services:
    composer.install:
        build: images/php-cli
        volumes:
            - ../crm:/app
        container_name: composer.install
        working_dir: /app
        command: composer install

    migrations:
        build: images/php-cli
        volumes:
            - ../crm:/app
        working_dir: /app
        container_name: 'migrations'
        command: "php bin/console doctrine:migrations:migrate -n"
        depends_on:
            - composer.install
            - postgres

    php-fpm:
        build: images/php-fpm
        ports:
            - '9000:9000'
        volumes:
            - ../crm:/app
            - ./fpm/www.conf:/etc/php/7.3/fpm/pool.d/www.conf
            - ./log/:/usr/log/
        working_dir: /app
        container_name: 'php-fpm'
        depends_on:
            - composer.install
            - migrations

    nginx:
        image: nginx
        container_name: 'nginx'
        working_dir: /app
        ports:
            - '8080:80'
        volumes:
            - ../crm:/app
            - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
        links:
            - php-fpm
            - postgres
        depends_on:
            - php-fpm

    postgres:
        image: postgres:12.1
        ports:
            - '5444:5432'
        container_name: 'postgresql'
        working_dir: /app
        restart: always
        environment:
            POSTGRES_DB: 'db_name'
            POSTGRES_USER: 'db_user'
            POSTGRES_PASSWORD: 'db_pass'
            PGDATA: '/var/lib/postgresql/data/pgdata'
        volumes:
            - ./data/dump:/app/dump
            - ./data/postgresql:/var/lib/postgresql/pgdata
