version: '3'
services:

    composer.install:
        image: akeneo/php
        volumes:
            - ../crm:/app
        container_name: composer.install
        working_dir: /app
        command: composer install

    php-fpm:
        image: akeneo/fpm
        ports:
            - '9000:9000'
        volumes:
            - ../crm:/app
            - ./fpm/www.conf:/etc/php/7.3/fpm/pool.d/www.conf
            - ./log/www.access.log:/usr/log/www.access.log
        working_dir: /app
        container_name: 'php-fpm'
        depends_on:
            - composer.install

    nginx:
        image: nginx
        container_name: 'nginx'
        working_dir: /app
        ports:
            - '80:80'
        volumes:
            - ../crm:/app
            - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
        links:
            - php-fpm
        depends_on:
            - composer.install
#
#    postgres:
#        image: postgres
#        ports:
#            - '5432:5432'
#        container_name: 'postgresql'
#        working_dir: /app
#        restart: always
#        environment:
#            POSTGRES_DB: 'db_name'
#            POSTGRES_USER: 'db_user'
#            POSTGRES_PASSWORD: 'db_pass'
#        volumes:
#            - ./data/dump:/app/dump
#            - ./data/postgresql:/var/lib/postgresql/data
