# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: false      # Automatically injects dependencies in your services.
        autoconfigure: false # Automatically registers your services as commands, event subscribers, etc.

    entity_manager_factory:
        shared: false
        class: Doctrine\ORM\EntityManager
        factory: ['@doctrine.orm.default_entity_manager', create]
        arguments:
            - "@doctrine.dbal.default_connection"
            - "@doctrine.orm.default_configuration"

    users.infrastructure:
        class: App\Crm\Users\Infrastructure\UserRepository
        factory: ['@entity_manager_factory', getRepository]
        arguments:
            - App\Crm\Users\Domain\Model\User

    users.registrar:
        class: App\Crm\Users\Domain\Action\UserRegistrar

    App\Controller\UserApiController:
        public: true
        arguments:
            - '@users.registrar'
        tags: ['controller.service_arguments']



