services:
    # infrastructure
    client.infrastructure.client_repository:
        class: App\Crm\Client\Infrastructure\ClientRepository
        factory: ['@entity_manager_factory', getRepository]
        arguments:
            - App\Crm\Client\Domain\Model\Client

    client.infrastructure.email_notificator:
        class: App\Crm\Client\Infrastructure\EmailNotificatorAdapter
        arguments:
            - "@mail_sender"

    client.infrastructure.sms_notificator:
        class: App\Crm\Client\Infrastructure\SmsNotificatorAdapter
        arguments:
            - "@sms_sender"

    # domain

    client.client_creator:
        class: App\Crm\Client\Domain\Service\ClientCreator
        arguments:
            - "@client.infrastructure.client_repository"

    client.client_finder:
        class: App\Crm\Client\Domain\Service\ClientFinder
        arguments:
            - "@client.infrastructure.client_repository"

    client.client_updater:
        class: App\Crm\Client\Domain\Service\ClientUpdater
        arguments:
            - "@client.infrastructure.client_repository"

    client.notificator_sender:
        class: App\Crm\Client\Domain\Service\NotificatorService
        arguments:
            - "@client.infrastructure.email_notificator"
            - "@client.infrastructure.sms_notificator"