doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'

        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        #server_version: '5.7'
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            Users:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Crm/Users/Domain/Model'
                prefix: 'App\Crm\Users\Domain\Model'
                alias: Users
            Client:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Crm/Client/Domain/Model'
                prefix: 'App\Crm\Client\Domain\Model'
                alias: Client
